[package]
name = "sonic"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.23.0"
gif = "0.11.4"
image = "0.24.2"

[workspace]
members = [
  "rsdk-extract",
  "processor",
  "sonic-bevy"
]
