[package]
name = "rsdk-extract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
byteorder = "1.4.3"
md5 = "0.7.0"
clap = "2.34.0"
log = "0.4.0"
env_logger = "0.9.0"